calculadorafatec/simulados/urls.py
from django.urls import path, include
from  . import views

app_name = 'simulados'


urlpatterns = [
    path('', views.home_simulados, name='home-simulados'),
    path('teste-simulado/', views.teste_simulado, name='teste-simulado'),
    path('simulado2/', views.simulado2, name='simulado2'),
    path('gabarito/', views.gabarito, name='gabarito'),

    # simulado endpoints
    path('simulado/<int:simulado_id>/start/', views.start_simulado, name='start-simulado'),
    path('simulado/<int:tentativa_id>/questao/<int:numero>/', views.exibir_questao, name='exibir-questao'),
    path('simulado/<int:tentativa_id>/responder/', views.responder_questao, name='responder-questao'),
    path('simulado/<int:tentativa_id>/finalizar/', views.finalizar_tentativa, name='finalizar-tentativa'),
    path('simulado/personalizado/criar/', views.criar_simulado_personalizado, name='criar-simulado'),
    path('simulado/<int:simulado_id>/ver/', views.ver_simulado, name='ver-simulado'),
]

calculadorafatec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls ),
    path('accounts/', include('allauth.urls')),
    path('', include('calculadorafatec.core.urls')),
    #path('simulados/', include('calculadorafatec.simulados.urls')),
    path('simulados/', include('calculadorafatec.simulados.urls', namespace='simulados')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calculadorafatec/core/models.py
from django.db import models
from django.template.defaultfilters import slugify
from calculadorafatec.core.managers import  KindQuerySet
from django.shortcuts import resolve_url as r
from .choices_disciplinas import ChoicesDisciplinas


# Create your models here.
class Regiao(models.Model):
    regiao = models.CharField(max_length=100) 
    
    def __str__(self):
        return self.regiao
       
class Disciplinas(models.Model):
    disciplina = models.CharField(verbose_name ="Disciplina", max_length=20, blank=True, null=True,)
    sigla = models.CharField(verbose_name ="Sigla",max_length=4, blank=True, null=True,)
    cor = models.CharField(verbose_name ="Cor",max_length=7, blank=True, null=True,)
    obs = models.TextField("Observação",  blank=True, null= True)
    quantidade_questoes = models.PositiveIntegerField(verbose_name ="Quantidade de questões", blank=True, null= True, default=0) 

    class Meta:
        verbose_name_plural = 'Disciplinas da prova'
        verbose_name = 'Diciplina da prova'
        ordering = ('disciplina',)

    def __str__(self):
        return self.disciplina

class EixoTecnologico(models.Model):
    eixo_tecnologico = models.CharField(max_length=100, blank=True)
    
    def __str__(self):
        return self.eixo_tecnologico

class Curso(models.Model):
    #cod_curso = models.PositiveIntegerField(primary_key=True) or cod_curso = models.AutoField(primary_key=True)
    curso = models.CharField(max_length=100, blank=True)
    eixo_tecnologico = models.ForeignKey(EixoTecnologico, blank=True, null=True, on_delete=models.SET_NULL)
    materia_1 = models.CharField('Materia peso 2 (1ª)', blank=True, max_length=4, choices=ChoicesDisciplinas.choices)
    materia_2 = models.CharField('Materia peso 2 (2ª)', blank=True, max_length=4, choices=ChoicesDisciplinas.choices)    
    #materia_3 = models.ManyToManyField(Disciplinas, blank=True, null=True) - Criar relacionemento com a tabela Disciplinas    
    visao_geral = models.TextField("Visão geral",  blank=True, null= True)
    conteudo_estudo = models.TextField("O aluno estuda",  blank=True, null= True)
    profissional_faz = models.TextField("O profisisonal faz", blank=True, null= True)
    mercado_trabalho = models.TextField("Mercado de trabalho", blank=True, null= True)
    destaque = models.TextField("Destaque",  blank=True, null= True)
    sugestao_cursos = models.TextField("Sugestões de cursos",  blank=True, null= True)
    #sugestao_cursos = models.ManyToManyField(Curso)    
    ativo = models.BooleanField('ativa',default=True)
    slug = models.SlugField(unique=True, blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Cursos'
        verbose_name = 'Curso'
        ordering = ('curso',)

    #attributes
    @property
    def cod_curso(self):
        return self.id
        #access it as curso.cod_curso where you would normally do curso.id

    def __str__(self) -> str:
        return self.curso

class Fatec(models.Model):
    #cod_instituicao = models.PositiveIntegerField(primary_key=True) or cod_instituicao = models.AutoField(primary_key=True)
    fatec = models.CharField(max_length=100, unique=True)
    institucional = models.CharField(max_length=100, blank=True)
    regiao = models.ForeignKey(Regiao, on_delete=models.SET_NULL, null=True, verbose_name='região')
    cidade = models.CharField(max_length=100, blank=True)
    endereco = models.CharField(max_length=150, blank=True)
    googlemaps_iframe = models.TextField(blank=True, null= True)
    googlemaps = models.URLField(blank=True)
    site = models.URLField(blank=True)
    data_inauguracao = models.DateField('Data de Inauguração', blank=True, null=True)
    criado_em = models.DateTimeField('criado em',auto_now=True)
    ativo = models.BooleanField('ativa',default=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    cursos= models.ManyToManyField(Curso,  blank=True) 
    imagem = models.ImageField('Fachada',upload_to="fatecs",blank=True, null=True)
    #imagem = models.ForeignKey( Imagem, on_delete=models.SET_NULL, null=True, related_name='Imagem', blank=True)

    class Meta:
        verbose_name_plural = 'Fatecs'
        verbose_name = 'Fatec'
        ordering = ('fatec',)

    def __str__(self) -> str:
        return f"{self.fatec} {self.institucional}"


    def get_absolute_url(self):
            return r('detalhes_fatec', slug=self.slug)

    def qtd_cursos(self):
        return Curso.objects.filter(fatec__id=self.id).count()

    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = slugify(self.fatec)
    #    return super().save(*args, **kwargs)        

class Contact(models.Model):
    EMAIL = 'E'
    PHONE = 'P'
    WHATSAPP = 'W'

    KINDS=(
        (EMAIL,'Email'),
        (PHONE,'Telefone'),
        (WHATSAPP,'Whatsapp'),
    )
    
    Fatec = models.ForeignKey('Fatec', on_delete=models.CASCADE, verbose_name='Fatec')
    kind = models.CharField('tipo', max_length=1, choices=KINDS)
    value = models.CharField('valor', max_length=255)

    objects = KindQuerySet.as_manager()
    class Meta:
        verbose_name_plural = 'contatos'
        verbose_name = 'contato'
    
    def __str__(self):
        return self.value  

class Social(models.Model):
    SITE = 'W'
    FACEBOOK = 'F'
    INSTAGRAM = 'I'
    YOUTUBE = 'Y'
    LINKEDIN = 'L'
    TWITTER = 'T'
    BLOG = 'B'
    OUTROS = 'O'

    KINDS=(
        (SITE,'Site'),
        (FACEBOOK,'Facebook'),
        (INSTAGRAM, 'Instagram'),
        (YOUTUBE, 'Youtube'),
        (LINKEDIN, 'Linkedin'),
        (TWITTER, 'Twitter'),        
        (BLOG, 'Blog'),
        (OUTROS,'Outros'),
    )
    
    Fatec = models.ForeignKey('Fatec', on_delete=models.CASCADE, verbose_name='Fatec')
    kind = models.CharField('tipo', max_length=1, choices=KINDS)
    value = models.CharField('valor', max_length=255)

    objects = KindQuerySet.as_manager()
    class Meta:
        verbose_name_plural = 'enderecos sociais'
        verbose_name = 'endereço social'
    
    def __str__(self):
        return self.value  

class ResultadoVestibularFatec(models.Model):
    cod_resultado_fatec = models.PositiveIntegerField(primary_key=True) 
    cod_curso = models.IntegerField(blank=True,null=True)
    cod_instituicao = models.IntegerField(blank=True,null=True)
    #cod_curso = models.ForeignKey(Curso, on_delete=models.SET_NULL, blank=True,null=True,)
    #cod_instituicao = models.ForeignKey(Fatec, on_delete=models.SET_NULL, blank=True,null=True,)
    ano = models.IntegerField()
    semestre = models.IntegerField()
    periodo = models.CharField(max_length=10)
    qtde_vagas = models.IntegerField()
    qtde_inscrito = models.IntegerField()
    demanda = models.FloatField()
    nota_corte = models.FloatField()
    nota_maxima = models.FloatField()

    class Meta:
        verbose_name_plural = 'resultados do vestibulares da fatec'
        verbose_name = 'resultado do vestibular da fatec'
    
    def nome_curso(self, id_ = 1): #teste
        cTeste = (Curso.objects.filter(id=id_).values('curso'))                
        return (Curso.objects.values('curso').get(pk=id_))        

    def __str__(self):
        return str(self.cod_resultado_fatec)

class ResultadoVestibularFatec2(models.Model):
    cod_resultado_fatec = models.PositiveIntegerField(primary_key=True) 
    cod_curso = models.ForeignKey(Curso, on_delete=models.SET_NULL, blank=True,null=True)
    cod_instituicao = models.ForeignKey(Fatec, on_delete=models.SET_NULL, blank=True,null=True)
    ano = models.IntegerField()
    semestre = models.IntegerField()
    periodo = models.CharField(max_length=10)
    qtde_vagas = models.IntegerField()
    qtde_inscrito = models.IntegerField()
    demanda = models.FloatField()
    nota_corte = models.FloatField()
    nota_maxima = models.FloatField()

       
    def __str__(self):
        return str(self.cod_resultado_fatec)    

calculadorafatec/simulados/models.py
from django.db import models
from django.template.defaultfilters import slugify
from calculadorafatec.core.models import Disciplinas
#from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone

class ProcessoSeletivoVestibularFatec(models.Model):
    ANALISE = 'AN'
    EXAME = 'EX'
    FORMATO_PROCESSO = [
        (ANALISE, 'Análise Histórico Escolar'),
        (EXAME, 'Exame'),    
    ]

    semestre = models.IntegerField(blank=True,null=True)
    ano  = models.IntegerField(blank=True,null=True)
    edicao =  models.CharField(verbose_name='edição',max_length=20, blank=True,null=True)    
    
    formato_processo = models.CharField(verbose_name='formato de seleção',
        max_length=2,
        choices=FORMATO_PROCESSO,
        default=EXAME,
    )  
    edital = models.FileField(upload_to="provas", blank=True,null=True) 
    data_prova = models.DateField('data do exame', blank=True, null=True)    
    link_prova = models.URLField(max_length=500, blank=True,null=True)
    prova = models.FileField(upload_to="provas", blank=True,null=True) 
    
    gabarito = models.FileField(upload_to="provas", blank=True,null=True) 
    total_vagas = models.IntegerField(verbose_name='total de vagas', blank=True,null=True)
    total_inscritos = models.IntegerField(verbose_name='total de inscritos', blank=True,null=True)
    qtde_questoes_anulada = models.IntegerField(verbose_name='quantidade de questões anuladas', blank=True,null=True)
    qtde_fatecs =  models.IntegerField(verbose_name='quantidade de fatecs no processo seletivo', blank=True,null=True)
    qtde_cursos = models.IntegerField(verbose_name='quantidade de cursos no processo seletivo', blank=True,null=True)
    simulado_gratuito = models.BooleanField('simulado gratuito',default=False)    
    slug = models.SlugField(unique=True, blank=True, null=True)        
    observacao = models.TextField("observação",  blank=True, null= True)
    criado_em = models.DateTimeField('criado em',auto_now=True)

    class Meta:
        verbose_name_plural = 'processos seletivos dos vestibulares da fatec'
        verbose_name = 'processo seletivo do vestibular da fatec'
        ordering = ('-semestre','-ano')
    
    def save(self, *args, **kwargs):
        if not self.edicao:
            self.edicao = f'{self.semestre}° semestre de {self.ano}'
        
        if not self.slug:
            self.slug = slugify(self.edicao)
        
        return super().save(*args, **kwargs)

    def __str__(self):
        return str(self.edicao)
    
class Questao(models.Model):
    processo = models.ForeignKey(ProcessoSeletivoVestibularFatec,
        on_delete=models.CASCADE,
        related_name="questoes"
    )
    
    numero = models.IntegerField(blank=True, null=True)
    enunciado = models.TextField()
    imagem = models.ImageField(upload_to="questoes", blank=True, null=True)

    disciplina = models.ForeignKey(
        Disciplinas,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    anulada = models.BooleanField(default=False)
    criado_em = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('processo', 'numero')
        ordering = ('numero',)

    def __str__(self):
        return f"Q{self.numero} - {self.processo.edicao or self.processo.slug or self.processo.ano}"



class Alternativa(models.Model):
    questao = models.ForeignKey(
        Questao, on_delete=models.CASCADE, related_name="alternativas"
    )
    letra = models.CharField(max_length=2, blank=True, null=True)
    texto = models.TextField()
    correta = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.letra} - Alternativa da Q{self.questao.numero}"


class SimuladoPersonalizado(models.Model):
    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    titulo = models.CharField(max_length=200)
    descricao = models.TextField(blank=True, null=True)
    criado_em = models.DateTimeField(auto_now_add=True)

    questoes = models.ManyToManyField(Questao, blank=True, related_name="simulados_personalizados")
    total_questoes = models.IntegerField(blank=True, null=True)
    nota_maxima = models.FloatField(blank=True, null=True)
    tempo_limite_minutos = models.IntegerField(blank=True, null=True)
    publico = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.titulo} ({self.user})"
    

class TentativaSimulado(models.Model):
    simulado = models.ForeignKey(SimuladoPersonalizado, on_delete=models.CASCADE, related_name="tentativas")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    iniciado_em = models.DateTimeField(auto_now_add=True)
    finalizado_em = models.DateTimeField(blank=True, null=True)
    tempo_segundos = models.IntegerField(blank=True, null=True)

    nota_final = models.FloatField(blank=True, null=True)

    def calcular_nota(self):
        respostas = self.respostas.all()
        total_questoes = respostas.count()
        corretas = sum(1 for r in respostas if r.correta)
        if total_questoes:
            self.nota_final = round((corretas / total_questoes) * 100, 2)
        else:
            self.nota_final = 0
        return self.nota_final

    def finalizar(self):
        self.finalizado_em = timezone.now()
        self.tempo_segundos = int((self.finalizado_em - self.iniciado_em).total_seconds())
        self.calcular_nota()
        self.save()

    def __str__(self):
        return f"{self.user} - {self.simulado.titulo} - {self.nota_final}"


class RespostaDoUsuario(models.Model):
    tentativa = models.ForeignKey(TentativaSimulado, on_delete=models.CASCADE, related_name="respostas")
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)    
    alternativa_marcada = models.ForeignKey(Alternativa, on_delete=models.SET_NULL, null=True)

    correta = models.BooleanField(default=False)
    marcado_em = models.DateTimeField(auto_now_add=True)
    class Meta:
        unique_together = ('tentativa', 'questao')

    def save(self, *args, **kwargs):
        if self.alternativa_marcada:
            self.correta = self.alternativa_marcada.correta
        else:
            self.correta = False            
        super().save(*args, **kwargs)
        
    def __str__(self):
        return f"Resposta de {self.tentativa.user} para Q{self.questao.numero}"

calculadorafatec/simulados/templates/gabarito.html
{% extends 'base.html' %}
{% load static %}
{% block 'head' %} 
    <meta name="description" content="Gabarito">
{% endblock %}

{% block 'title' %}Gabarito{% endblock %}

{% block 'body' %}
<div class="container">  

</div>
{% endblock %}

calculadorafatec/simulados/templates/index-simulados.html
{% extends 'base.html' %}
{% load static%}

{% block 'head' %} 
    <meta name="description" content="Calculadora Fatec é uma ferramenta para auxiliar candidatos a ingressarem nas instituições Fatecs. Armazenamos todas as demandas e notas de cortes dos vestibulares e expertize para conduzir um melhor resultado para o vestibular. Por isso, Calculadora Fatec, quem usa, sabe. Assine agora o serviço e se aproxime do seu objetivo em ser um aluno da Fatec. VEM PRA FATEC! Os candidatos podem usar a ferramenta para Calcular a Nota do Vestibular, Consultar os Guias de Fatecs e Cursos e prepare-se melhor para o exame do Vestibular.">
{% endblock %}

{% block 'title' %}Simulados: Calculadora FATEC::Quem Usa, SABE! {% endblock %}

{% block 'body' %}
<div class="container">    
    <div class="px-4 py-5 my-5 text-center bg-body rounded shadow-sm ">
        <img class="d-block mx-auto mb-4" src="{% static 'core/img/calculadora.png' %}" alt="" />
        <h1 class="display-5 fw-bold text-dark">Simulados da Calculadora Fatec</h1>      
        <p>
            Defina como deseja preparar o seu simulado para continuar o seus estudos.
        </p> 
        <div class="col-lg-6 mx-auto">
            <form  action="{% url 'simulados:teste-simulado' %}" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                <div class="input-group input-group-lg my-3">
                    <select class="form-select" id="cod_curso" name="cod_curso" required="required">
                        <option selected value="0">Escolha o curso...</option>
                            {% for curso in cursos %}
                                <option value="{{ curso.id }}" data-mat1="{{ curso.materia_1 }}" data-mat2="{{ curso.materia_2 }}" >{{curso}}</option>
                            {% empty %}
                                <option value="0">Não tem nenhum curso disponível</option>                        
                            {% endfor %}                  
                    </select>                
                </div>    
                <div class="input-group input-group-lg my-3">
                    <select class="form-select" name="prova_vestibular" id="prova_vestibular" required="required">
                        <option value="0">Selecione a edição do vestibular</option>
                        {% for p in processos_seletivos %} 
                            <option data-ano="{{ p.ano }}" data-semestre="{{ p.semestre }}" value="{{ p.semestre }}-{{ p.ano }}" {% if not p.simulado_gratuito %} disabled {% endif %}>{{ p.edicao }}</option>
                         {% empty %}
                         <option value="0">Não tem processos seletivos disponíveis</option>                        
                        {% endfor %}                                                                              
                    </select>
                    {% comment "Não consegui implementar com o a estrutura do optgroup" %}
                        <select class="form-select" >
                            <option value="0">Selecione a prova do vestibular</option>
                            <optgroup label="Simulados Gratuitos">
                                <option value="12009">1º Semestre - 2009</option>
                                ...                   
                            </optgroup>
                            <optgroup label="Simulados Assinantes" class="assinantes">
                                ...
                                <option value="12023" disabled="disabled">1º Semestre de 2023</option>                          
                            </optgroup>                                                      
                        </select>
                    {% endcomment %}                    
                </div>            
                <input type="submit" class="btn w-100 btn-primary my-3 btn-lg" value="Iniciar simulado" />            
            </form> 
        </div>
    </div>  
    <hr class="my-4" />    
    <br />
</div>    

{% endblock %}

calculadorafatec/simulados/templates/simulado.html
{% extends 'base.html' %}
{% load static %}


{% block 'head' %} 
    <meta name="description" content="Calculadora Fatec é uma ferramenta para auxiliar candidatos a ingressarem nas instituições Fatecs. Armazenamos todas as demandas e notas de cortes dos vestibulares e expertize para conduzir um melhor resultado para o vestibular. Por isso, Calculadora Fatec, quem usa, sabe. Assine agora o serviço e se aproxime do seu objetivo em ser um aluno da Fatec. VEM PRA FATEC! Os candidatos podem usar a ferramenta para Calcular a Nota do Vestibular, Consultar os Guias de Fatecs e Cursos e prepare-se melhor para o exame do Vestibular.">
{% endblock %}

{% block 'title' %}Simulado {{ prova_vestibular_edicao }} - {{ curso }} -  Calculadora Fatec{% endblock %}

{% block 'body' %}
<div class="container">   
    <div class="px-4 py-5 my-5  bg-body rounded shadow-sm ">
        <h1 class="display-5 fw-bold text-dark text-center">Simulado escolhido {{ prova_vestibular_edicao }}</h1>      
        <h2>Parâmetros</h2>
        <ul>
            <li>Semestre: {{ prova_vestibular_edicao.semestre }}</li>
            <li>Ano: {{ prova_vestibular_edicao.ano }}</li>
            <li>Prova: <a href="{{ prova_vestibular_edicao.link_prova }}" target="_blank" >Acessar</a></li>
            <li>Gabarito: <a href="{{ prova_vestibular_edicao.gabarito.url }}" target="_blank" >Acessar</a></li>


            <li>Curso: {{ curso }} -  {{ curso.eixo_tecnologico }} </li>

            <li>1ª Matéria de peso 2: {{ curso.get_materia_1_display|title}}</li>
            <li>2º Matéria de peso 2: {{ curso.get_materia_2_display|title }}</li>
        </ul>
      
    </div>
    <hr class="my-4" />    
    <br />    
</div>
{% endblock %}

calculadorafatec/simulados/templates/simulado2.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %} 
    <meta name="description" content="Simulado">
    <link href="{% static 'simulados/css/main.css' %}" rel="stylesheet" />

{% endblock %}

{% block 'title' %}Realizar o simulado do 1º semestre de 2010 - Análise e Desenvolvimento de Sistemas{% endblock %}

{% block 'body' %}
<div class="container-fluid">  
    <div class="page-header">
        <h1 class="text-center ">Simulado do Vestibular<span class="xs-hidden"> Fatec </span>do 1º semestre de 2010</h1>
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text">Navegador de Questão: </span>
        <input type="number"  min="1" max="54" class="form-control" placeholder="Informe o número da questão" id="navegador_questao" />
    </div>
    <div class="alert alert-info">
        <div class="container">
            <h2>clique sobre o número para navegar na questão</h2>            
            <ul class="nav nav-pills not-response" >
                {% for i in total_questoes %}
                <li>
                    <a href="#" class="btn btn-danger" ><span class="badge">{{ i }}</span></a>
                </li>  
                {% empty %}
                    <li>Nenhuma questão foi localizada</li>
                {% endfor %}                
            
            </ul>             
        </div>
    </div>    
    <div class="prova" >
        <div class="quadro-perguntas">
            {% for d in disciplinas %}
                {% if d.disciplina|lower in "Raciocínio Lógico"|lower %}
                    <h2 class="text-center destaque-materia py-2" style="background:{{d.cor}}">{{ d.disciplina }}<span class="ms-2 badge-simulado badge text-bg-info">1/54</span></h2>
                {% endif %}
            {% endfor %}
            <p class="lead text-justify" ><b>1)</b>
                PERGUNTA BLABLABLA</p>                

                <div class="col-md-12 col-xs-12 col-sm-12 box-alternativas px-4 py-5 my-5  bg-body rounded shadow-sm ">
                    <form class="opc-alternativas">
                        <label class="organizador-alternativa">
                            <input type="radio" name="alternativa" value="A" class="alternativa" checked="checked" />
                            <b>A) </b><span>Alternativa A</span>
                            <span class="checkmark"></span>
                        </label><br />
                        <label class="organizador-alternativa">
                            <input type="radio" name="alternativa" value="B" class="alternativa" />
                            <b>B) </b><span>Alternativa B</span>
                            <span class="checkmark"></span>
                        </label><br />
                        <label class="organizador-alternativa">
                            <input type="radio" name="alternativa" value="C" class="alternativa" />
                            <b>C) </b><span>Alternativa C</span>
                            <span class="checkmark"></span>
                        </label><br>
                        <label class="organizador-alternativa">
                            <input type="radio" name="alternativa" value="D" class="alternativa" />
                            <b>D) </b><span>Alternativa D</span>
                            <span class="checkmark"></span>
                        </label><br />
                        <label class="organizador-alternativa">                            
                            <input type="radio" name="alternativa" value="E" class="alternativa" />
                            <b>E) </b><span>Alternativa E</span>
                            <span class="checkmark"></span>
                        </label>
                    </form>
                </div>            
                               
        </div>
        <div class="controls-btn col-md-12 col-xs-12 col-sm-12">
            <button {% if currentPage == 1 %} disabled {% endif %} onclick="goPreviousPage(currentPage-1);" class="btn btn-primary btn-lg  ">
                &laquo; Anterior
            </button>
           
            <button  {% if currentPage >= pageSize %} disabled {% endif %}  onclick="salvarResposta();goNextPage(currentPage+1);" class="btn btn-primary btn-lg" >
                Próximo &raquo;
            </button>
        </div>
    </div>

   
</div>
{% endblock %}