calculadorafatec/core/urls.py
from django.urls import path, include
from  . import views

urlpatterns = [
    path('', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('calculadora/', views.calculadora, name='calculadora'),
    path('materias-prova-peso2/', views.materias_prova_peso2, name='materias-prova-peso2'),
    path('materias-prova-peso2-com-js/', views.materias_prova_peso2_com_js, name='materias-prova-peso2-com-js'),
    path('cursos/', views.cursos, name='cursos'),
    path('fatecs/', views.fatecs, name='fatecs'),
    path('busca-slug-fatec/', views.busca_slug_fatec, name="busca_slug_fatec"), # intermediária. Usava para capturar o slug
    #path('detalhes-fatec/<int:id>', views.detalhes_fatec, name="detalhes_fatec"),
    path('detalhes-fatec/<slug:slug>/', views.detalhes_fatec, name="detalhes_fatec"),
    #path('detalhes-fatec/', views.detalhes_fatec, name="detalhes_fatec"),
    path('busca-slug-curso/', views.busca_slug_curso, name="busca_slug_curso"), # intermediária. Usava para capturar o slug
    path('detalhes-curso/<slug:slug>/', views.detalhes_curso, name="detalhes_curso"),
    path('nota-de-corte/', views.nota_de_corte, name='nota-de-corte'),
    path('detalhes-nota-de-corte/', views.detalhes_nota_de_corte, name='detalhes-nota-de-corte'),
    path('busca-cursos-da-fatec/', views.busca_cursos_da_fatec, name='busca-cursos-da-fatec'),

    path('contato/', views.contato, name='contato'),
    path('logout/', views.logout, name='logout'),
]

calculadorafatec/simulados/urls.py
from django.urls import path, include
from  . import views

app_name = 'simulados'


urlpatterns = [
    path('', views.home_simulados, name='home-simulados'),
    path('teste-simulado/', views.teste_simulado, name='teste-simulado'),
    path('simulado2/', views.simulado2, name='simulado2'),
    path('gabarito/', views.gabarito, name='gabarito'),

    # simulado endpoints
    path('simulado/<int:simulado_id>/start/', views.start_simulado, name='start-simulado'),
    path('simulado/<int:tentativa_id>/questao/<int:numero>/', views.exibir_questao, name='exibir-questao'),
    path('simulado/<int:tentativa_id>/responder/', views.responder_questao, name='responder-questao'),
    path('simulado/<int:tentativa_id>/finalizar/', views.finalizar_tentativa, name='finalizar-tentativa'),
    path('simulado/personalizado/criar/', views.criar_simulado_personalizado, name='criar-simulado'),
    path('simulado/<int:simulado_id>/ver/', views.ver_simulado, name='ver-simulado'),
]

calculadorafatec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls ),
    path('accounts/', include('allauth.urls')),
    path('', include('calculadorafatec.core.urls')),
    #path('simulados/', include('calculadorafatec.simulados.urls')),
    path('simulados/', include('calculadorafatec.simulados.urls', namespace='simulados')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calculadorafatec/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    """
    Modelo customizado de usuário.
    Herdamos de AbstractUser porque mantém:
      - username
      - first_name
      - last_name
      - email
      - password
      - is_staff, is_active...
      - groups/perms
    Mas permite adicionar novos campos.
    """
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)

    cpf = models.CharField(
        max_length=11,
        unique=True,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.username or self.email

calculadorafatec/accounts/forms.py
from allauth.account.forms import SignupForm
from django import forms

class CustomSignupForm(SignupForm):
    cpf = forms.CharField(
        max_length=11,
        required=True,
        label="CPF"
    )
    avatar = forms.ImageField(
        required=False,
        label="Foto de perfil"
    )

    def save(self, request):
        user = super().save(request)

        user.cpf = self.cleaned_data["cpf"]
        user.avatar = self.cleaned_data.get("avatar")
        user.save()

        return user

calculadorafatec/accounts/views.py
from django.shortcuts import render

calculadorafatec/core/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
#Django Messages - definida lá no settings - MESSAGES_TAG
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.contrib.messages import constants
from calculadorafatec.core.models import Curso, Fatec, ResultadoVestibularFatec, ResultadoVestibularFatec2, EixoTecnologico, Social, Contact
from django.conf import settings
from django.core.paginator import (
    Paginator,
    EmptyPage,
    PageNotAnInteger,
)
from django.core import serializers
import json
from django.contrib.auth.decorators import login_required



def home(request):
    #fatecs = []
    fatecs = ['Fatec Sorocaba', 'Fatec São Roque' , 'Fatec São Paulo', 'Fatec Itu', 'Fatec Carapicuíba']

    if request.method == "POST":
            nome = request.POST.get("nome")
            return render(request,'index.html',{'nome':nome,'fatecs':fatecs})
    return render(request,'index.html',{'fatecs':fatecs})


def calculadora(request):
    return render(request,'calculadora.html')


def fatecs(request):
    #fatecs = ['Fatec Sorocaba', 'Fatec São Roque' , 'Fatec São Paulo', 'Fatec Itu', 'Fatec Carapicuíba']
    fatecs = Fatec.objects.all()
    return render(request,'fatecs.html',{'fatecs':fatecs})


def busca_slug_fatec(request):
    id = request.GET.get('cod_fatec')
    if id != "0":
        fatec = get_object_or_404(Fatec, id=id) #capturar a excessão aqui
        return redirect('detalhes_fatec', fatec.slug)    
    return redirect('fatecs')    


def detalhes_fatec(request, slug):
    fatec = get_object_or_404(Fatec, slug=slug)   
    #fatec.imagem = f'{settings.MEDIA_URL}{fatec.imagem}' Esse item eu forçava o uso do midia. Porém o tipo do campo tem um atributo . url que fornece o path completo.
    cursos = Curso.objects.filter(fatec__id=fatec.id)
    socialmedia =  Social.objects.filter(Fatec_id=fatec.id)
    fb = socialmedia.facebooks()
    contatos =  Contact.objects.filter(Fatec_id=fatec.id)
    resultados_cursos = ResultadoVestibularFatec.objects.filter(cod_instituicao=fatec.id).order_by('-ano', '-semestre')
    resultados_cursos2 = ResultadoVestibularFatec2.objects.filter(cod_instituicao=fatec.id).order_by('cod_curso_id','periodo','-ano', '-semestre')
    demanda = {}
    for resultado in resultados_cursos2:        
        r = {}
        curso_periodo_key = ' - '.join([str(resultado.cod_curso),resultado.periodo])
        
        if curso_periodo_key not in demanda:
            demanda[curso_periodo_key] = []            
              
        if curso_periodo_key in demanda:
            r = {
                "curso": str(resultado.cod_curso),
                "id_curso": resultado.cod_curso_id,
                "periodo": resultado.periodo,
                "ano": resultado.ano,
                "semestre":resultado.semestre,
                "qtde_vagas": resultado.qtde_vagas,
                "qtde_inscrito": resultado.qtde_inscrito,
                "demanda": resultado.demanda,            
            }
            demanda[curso_periodo_key].append(r)
    
    # print(demanda)
    # for key, value in demanda.items():
    #     print((value))
        
    return render(request,'detalhes-fatec.html', {
        'detalhe': fatec,'cursos':cursos, 
        'redessociais': socialmedia, 'facebook':fb, 'contatos': contatos, 
         "demandasCursos":  demanda
        })   


def busca_slug_curso(request):
    id = request.GET.get('cod_curso')
    if id != "0":
        curso = get_object_or_404(Curso, id=id) #capturar a excessão aqui
        return redirect('detalhes_curso', curso.slug)    
    return redirect('cursos')    


def detalhes_curso(request, slug):
    curso = get_object_or_404(Curso, slug=slug) 
    fatecs = Fatec.objects.filter(cursos=curso.id)
    return render(request,'detalhes-curso.html', {'detalhe': curso,'fatecs':fatecs })   


def cursos(request):
    #cursos = ['Análise e Desenvolvimento de Sistemas', 'Sistemas para Internet' , 'Desenvolvimento Multiplataforma', 'Ciência de Dados', 'Sistemas Navais']
    cursos = Curso.objects.filter(ativo=True)
    return render(request,'cursos.html',{'cursos':cursos})


def materias_prova_peso2_com_js(request):
    return render(request,'materias-peso2-com-js.html')


def materias_prova_peso2(request):
    default_items_per_page = 5
    default_page = 1
    
    try:
        page = request.GET.get('page', default_page)    
    except:
        page = 1

    eixo_filtrar = request.GET.get('eixo-texnologico')
    nome_curso_filtrar = request.GET.get('nome-curso')

    cursos = Curso.objects.all()

    if eixo_filtrar:
        cursos = cursos.filter(eixo_tecnologico = eixo_filtrar)
    else:
        eixo_filtrar = 0
    
    if nome_curso_filtrar:
        #cursos = cursos.filter(curso__unaccent__icontains=nome_curso_filtrar) precisa usar o postgress https://docs.djangoproject.com/en/4.1/ref/contrib/postgres/lookups/
        cursos = cursos.filter(curso__icontains = nome_curso_filtrar)   
    else:
        nome_curso_filtrar = ""

    eixo_tecnologicos = EixoTecnologico.objects.all()    

    # Paginate items    
    try:
        items_per_page = request.GET.get('quantidades_cursos', default_items_per_page)    
    except:
        items_per_page = 5    
    #items_per_page = request.GET.get('quantidades_cursos') if request.GET.get('quantidades_cursos') else 2    
    
    paginator = Paginator(cursos, items_per_page)  
    
    try:
        items_cursos_page = paginator.page(page)
    except PageNotAnInteger:
        items_cursos_page = paginator.page(default_page)
    except EmptyPage:
        items_cursos_page = paginator.page(paginator.num_pages)          

    # Provide filtered, paginated library items
    
    return render(request,'materias-peso2.html',{'cursos':cursos, 'eixo_tecnologicos':eixo_tecnologicos,'items_cursos_page':items_cursos_page, 'pesquisa_nome_curso':nome_curso_filtrar, 'pesquisa_eixo_tecnologico': int(eixo_filtrar), 'items_per_page':int(items_per_page)  })


def contato(request):
    return redirect('https://wa.me/5515981057742')

@login_required(redirect_field_name='', login_url="login")
def nota_de_corte(request):
    fatecs = Fatec.objects.all()
    cursos = Curso.objects.filter(ativo=True)
    return render(request,'nota-de-corte.html',{'fatecs':fatecs, 'cursos':cursos})

@login_required(redirect_field_name='', login_url="login")
def detalhes_nota_de_corte(request):    
    fatec_id = request.POST.get('cod_fatec')
    if fatec_id == "0":
        return redirect('nota-de-corte')        

    curso_id = request.POST.get('cod_curso')
    fatec = get_object_or_404(Fatec, id=fatec_id)  

    
    resultados_cursos2 = ResultadoVestibularFatec2.objects.filter(cod_instituicao=fatec_id).order_by('cod_curso_id','periodo','-ano', '-semestre')
    
    if curso_id != "0":
        resultados_cursos2 = resultados_cursos2.filter(cod_curso=curso_id)

    demanda = {}
    for resultado in resultados_cursos2:        
        r = {}
        curso_periodo_key = ' - '.join([str(resultado.cod_curso),resultado.periodo])
        
        if curso_periodo_key not in demanda:
            demanda[curso_periodo_key] = []            
              
        if curso_periodo_key in demanda:
            r = {
                "curso": str(resultado.cod_curso),
                "id_curso": resultado.cod_curso_id,
                "periodo": resultado.periodo,
                "ano": resultado.ano,
                "semestre":resultado.semestre,
                "qtde_vagas": resultado.qtde_vagas,
                "qtde_inscrito": resultado.qtde_inscrito,
                "demanda": resultado.demanda,
                "nota_corte":resultado.nota_corte,
                "nota_maxima":resultado.nota_maxima                
            }
            demanda[curso_periodo_key].append(r)    
    return render(request,'detalhes-nota-de-corte.html', {"fatec":fatec, "demandasCursos":  demanda})


def busca_cursos_da_fatec(request):    
    id = request.POST.get('fatec_id')    
    cursos = Curso.objects.filter(fatec__id=id)
    cursos_json = json.loads(serializers.serialize('json',cursos))
    cursos_json_completo = [{'fields': curso['fields'],'id': curso['pk'], 'curso': curso['fields']['curso']} for curso in cursos_json]
    cursos_json = [{'id': curso['pk'], 'curso': curso['fields']['curso']} for curso in cursos_json]
    print(cursos_json)
    data = {'cursos':cursos_json,}
    return JsonResponse(data)
    

def login(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect(reverse('home'))       
        return render(request,'registration/login.html' )                    
    elif request.method =="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)

        if not user:
            messages.add_message(request, constants.ERROR, 'Usuário inválido!')
            return redirect(reverse('login'))        
        auth.login(request,user)
        #messages.add_message(request, constants.SUCCESS, 'Usuário logado com sucesso!')
        return redirect(reverse('home'))

def logout(request):
    auth.logout(request)    
    request.session.flush()
    return redirect(reverse('login'))

calculadorafatec/templates/base-login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="author" content="GregMaster" />
    
    <title>{% block 'title' %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"  rel="stylesheet"  />
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <meta name="theme-color" content="#122A59">

    {% block 'head' %}   {% endblock %}
  </head>
  <body id="body-pd">
    
    {% block 'body' %}   
    {% endblock %}
   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
  
  </body>
</html>

calculadorafatec/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="author" content="GregMaster, Gregorio Queiroz">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <meta name="keywords" content="Calcular Nota, Estimar Nota Fatec, Fatec, Vestibular Fatec, Calculadora Fatec, Fatecano, Prova da Fatec, Faculdade de Tecnologia do Estado de São Paulo, ensino superior, gratuito, curso, faculdade, faculdade gratuíta, ensino público, Calendário Fatec, Fatec inscrições, Prova Fatec, GregMaster, Fatec São Paulo, Fatec Sorocaba, Fatec Osasco, Fatec Carapicuíba, Guia de Profissões Fatecs, Guia de Cursos">    

    {% block 'head' %}   {% endblock %}
    <title>{% block 'title' %}   {% endblock %}</title>
  </head>
  <body class="fundo">
    {% include 'nav.html'  %}
    
    {% block 'body' %}   
    {% endblock %}
    {% include 'footer.html' only %}
       
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>    
  </body>
</html>

calculadorafatec/templates/footer.html
{% load filters %}
{% get_ano_calculadora as ano %}
<div class="container">
    <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
      </ul>
      <p class="text-center text-muted">©{{ ano }} Calculadora Fatec por GregMaster</p>
      <p class="text-center text-muted">{% now "Y" as current_year %} Copyright {{ current_year }}</p>

    </footer>
</div>

calculadorafatec/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-nav">
    <div class="container">
      <a href="{% url 'home' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <img class="my-2" src="{% static 'core/img/calculadora.png' %}" alt=""   height="32" role="img" />
      </a>      
      <a class="navbar-brand" href="{% url 'home' %}">CALCULADORA FATEC</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Recursos
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'calculadora' %}">Calculadora</a></li>
              <li><a class="dropdown-item" href="{% url 'fatecs' %}">Fatecs - Unidades</a></li>               
              <li><a class="dropdown-item" href="{% url 'cursos' %}">Cursos</a></li> 
              <li><a class="dropdown-item" href="{% url 'materias-prova-peso2' %}">Matérias de peso 2 por curso</a></li>     
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'nota-de-corte' %}">Nota de Corte</a></li>
              <li><a class="dropdown-item" href="{% url 'simulados:home-simulados' %}">Simulados</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Materiais úteis
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="https://calculadorafatec.gregmaster.com.br/folha-redacao.pdf" target="_blank">Folha de Redação</a></li>
              <li><a class="dropdown-item" target="_blank" href="t.me/CalculadoraFatec">Canal Telegram</a></li>               
              <li><a class="dropdown-item" target="_blank" href="https://www.youtube.com/channel/UCPY-NybV8D-K-tFXRoMLUew">Canal Youtube</a></li>  
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Grupo Whatsapp</a></li>
              <li><a class="dropdown-item" target="_blank" href="https://hotmart.com/pt-br/marketplace/produtos/o-guia-definitivo-para-ser-aprovado-no-vestibular-da-fatec-dicas-informacoes-e-ferramentas-essenciais-para-o-candidato-da-fatec/T11263966A">Guia Completo</a></li>
            </ul>
          </li>          
          <li class="nav-item">
              <a class="nav-link " aria-current="page" href="{% url 'contato' %}" target="_blank">Contato</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'admin:index' %}" target="_blank">Admin</a>
        </li> 
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link active" aria-current="page" href="{% url 'logout' %}" >Logout <small>({{ user.username }})</small></a>
          {%else %}       
            <a class="nav-link px-3" href="{% url 'login' %}">Log In</a>
          {% endif %}               
        </li>    
      </div>
    </div>
  </nav>